# Generated by Django 2.0.5 on 2018-06-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ts', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('create_dedicated_channel', models.BooleanField(default=False)),
                ('dedicated_channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('permalink', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('outage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Outage')),
            ],
        ),
    ]
