# Generated by Django 2.1.3 on 2018-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sales_notified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
