# Generated by Django 2.2.7 on 2019-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slackbot", "0002_announcement_sales_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="b2b_notified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
