# Generated by Django 2.0.5 on 2018-06-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Outage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(max_length=3000)),
                (
                    "sales_affected",
                    models.CharField(
                        choices=[("YE", "Yes"), ("NO", "No"), ("UN", "Unsure")],
                        default="UN",
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("eta", models.IntegerField(default=0)),
                (
                    "communication_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicate_outages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outage_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solves_outages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-pk"]},
        ),
        migrations.CreateModel(
            name="OutageHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(max_length=3000)),
                (
                    "sales_affected",
                    models.CharField(
                        choices=[("YE", "Yes"), ("NO", "No"), ("UN", "Unsure")],
                        default="UN",
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("eta", models.IntegerField(default=0)),
                (
                    "change_desc",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "communication_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_comunicate_outages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_outage_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_outage",
                        to="core.Outage",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_outage_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_solves_outages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-pk"]},
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(max_length=3000)),
                (
                    "resolved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("solving_time", models.IntegerField(default=0)),
                (
                    "suggested_outcome",
                    models.CharField(
                        choices=[
                            ("PM", "Postmortem report"),
                            ("MT", "Meeting to discuss"),
                            ("NO", "None"),
                        ],
                        default="NO",
                        max_length=2,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outage_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Outage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="systems_affected",
            field=models.ManyToManyField(to="core.System"),
        ),
        migrations.AddField(
            model_name="outage",
            name="systems_affected",
            field=models.ManyToManyField(to="core.System"),
        ),
    ]
