# Generated by Django 2.0.5 on 2018-06-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name']},
        ),
    ]
