# Generated by Django 2.0.5 on 2018-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_notification")]

    operations = [
        migrations.AlterModelOptions(
            name="notification", options={"ordering": ["-pk"]}
        ),
        migrations.AlterField(
            model_name="solution",
            name="summary",
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
