# Generated by Django 2.0.5 on 2018-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180725_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='report_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
