# Generated by Django 2.0.5 on 2018-07-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solution_report_url'),
        ('core', '0010_auto_20180730_0810'),
    ]

    operations = [
    ]
