# Generated by Django 2.0.5 on 2018-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0014_auto_20180802_1301")]

    operations = [
        migrations.AlterField(
            model_name="outage",
            name="eta",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="outagehistory",
            name="eta",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
