# Generated by Django 2.0.5 on 2018-08-20 11:10

from django.db import migrations, models
import django.utils.timezone

def fix_outage_started_at(apps, schema_editor):
    Outage = apps.get_model('core', 'Outage')
    for outage in Outage.objects.all():
        outage.started_at = outage.created
        outage.save()
    OutageHistory = apps.get_model('core', 'OutageHistory')
    for outage in OutageHistory.objects.all():
        outage.started_at = outage.created
        outage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180814_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='outage',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outagehistory',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(fix_outage_started_at),
    ]
