# Generated by Django 2.0.5 on 2018-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_notification_created_by")]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="summary",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="solutionhistory",
            name="summary",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
