# Generated by Django 2.1.3 on 2019-02-12 08:10

from django.db import migrations, models
import django.db.models.deletion


def migrate_systems_affected(apps, schema_editor):
    System = apps.get_model('core', 'System')
    OutageHistory = apps.get_model('core', 'OutageHistory')
    for system in System.objects.all():
        for outage in system.outage_set.all():
            outage.systems_affected = system
            outage.save()
            for outage_history in OutageHistory.objects.filter(outage_id=outage.id):
                outage_history.systems_affected = system
                outage_history.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181122_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outage',
            old_name='systems_affected',
            new_name='systems_affected_bck',
        ),
        migrations.RenameField(
            model_name='outagehistory',
            old_name='systems_affected',
            new_name='systems_affected_bck',
        ),
        migrations.AddField(
            model_name='outage',
            name='systems_affected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems_outage', to='core.System'),
        ),
        migrations.AddField(
            model_name='outagehistory',
            name='systems_affected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems_outagehistory', to='core.System'),
        ),
        migrations.RunPython(migrate_systems_affected),
    ]
