# Generated by Django 2.1.3 on 2019-03-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0024_auto_20190212_1612")]

    operations = [
        migrations.CreateModel(
            name="PostmortemNotifications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_notified", models.BooleanField(default=False)),
                ("email_notified", models.BooleanField(default=False)),
                ("label_notified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="solution",
            name="postmortem_notifications",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.PostmortemNotifications",
            ),
        ),
    ]
