# Generated by Django 2.2 on 2019-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0028_auto_20190212_0957")]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
