# Generated by Django 2.2 on 2019-05-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0028_auto_20190212_0957")]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="prompt_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="outage",
            name="prompt_for_eta_update",
            field=models.BooleanField(default=True),
        ),
    ]
