# Generated by Django 2.2 on 2019-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0029_auto_20190521_0802")]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="communication_assignee_last_notified",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
