# Generated by Django 2.2 on 2019-06-12 10:01

from django.db import migrations, models


def init_resolved_field(apps, schema_editor):
    Outage = apps.get_model("core", "Outage")
    for outage in Outage.objects.filter(solution__isnull=False):
        outage.resolved = True
        outage.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0030_outage_communication_assignee_last_notified")]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(init_resolved_field),
    ]
