# Generated by Django 2.2.4 on 2019-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20190827_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outage",
            name="lost_bookings_choice",
            field=models.CharField(
                choices=[
                    ("0%", "0%"),
                    ("<10%", "<10%"),
                    ("<30%", "<30%"),
                    ("<60%", "<60%"),
                    ("<100%", "<100%"),
                    ("100%", "100%"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="outagehistory",
            name="lost_bookings_choice",
            field=models.CharField(
                choices=[
                    ("0%", "0%"),
                    ("<10%", "<10%"),
                    ("<30%", "<30%"),
                    ("<60%", "<60%"),
                    ("<100%", "<100%"),
                    ("100%", "100%"),
                ],
                max_length=5,
            ),
        ),
    ]
