# Generated by Django 2.2 on 2019-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0032_auto_20190827_0728")]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="announce_on_statuspage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="announce_on_statuspage",
            field=models.BooleanField(default=False),
        ),
    ]
