# Generated by Django 2.2 on 2019-08-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0033_auto_20190612_0706")]

    operations = [
        migrations.CreateModel(
            name="RootCause",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="outage",
            name="root_cause",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.RootCause",
            ),
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="root_cause",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.RootCause",
            ),
        ),
    ]
