# Generated by Django 2.2.7 on 2019-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_sales_impact_less_10"),
    ]

    operations = [
        migrations.AddField(
            model_name="outage",
            name="b2b_partners_affected_choice",
            field=models.CharField(
                choices=[("Y", "yes"), ("N", "no"), ("UN", "unknown")],
                default="UN",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="outagehistory",
            name="b2b_partners_affected_choice",
            field=models.CharField(
                choices=[("Y", "yes"), ("N", "no"), ("UN", "unknown")],
                default="UN",
                max_length=2,
            ),
        ),
    ]
