# Generated by Django 2.0.5 on 2018-07-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=1000)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        ),
    ]
